# Generated by Django 3.2.4 on 2021-09-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thedailynewspaper', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thedailynewspaper.news')),
            ],
        ),
    ]
