# Generated by Django 3.2.4 on 2021-10-03 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thedailynewspaper', '0004_notification_slider_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='world',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpic', models.ImageField(default='', upload_to='static/world/')),
                ('wheadlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thedailynewspaper.news')),
            ],
        ),
    ]
