# Generated by Django 3.2.4 on 2021-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedailynewspaper', '0007_delete_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='publishad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('advdes', models.TextField(max_length=800)),
                ('banner', models.ImageField(default='', upload_to='static/publishbanner/')),
            ],
        ),
    ]
