# Generated by Django 3.2.4 on 2021-10-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thedailynewspaper', '0010_world_wcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='wcategory',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.CASCADE, to='thedailynewspaper.category'),
        ),
    ]
